name: nodejs test + benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['latest']

    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: latest

    - name: install
      #run: pnpm ci # needs package-lock.json
      run: pnpm install

    - name: build
      run: pnpm run build --if-present

    - name: test
      run: pnpm run test

    - name: benchmark
      run: pnpm run test:perf:save

    - name: update doc/benchmarks.json
      # https://github.com/marketplace/actions/add-commit
      uses: EndBug/add-and-commit@v9.1.0
      with:
        add: doc/benchmarks.json
        author_name: GitHub Actions
        author_email: actions@github.com
        message: update doc/benchmarks.json
